config/routes.rb
HotelNagano::Application.routes.draw do

  resources :billing

  namespace :admin do
    resources :clients
    resources :reservations
    resources :rooms
    resources :statistics
  end

  resources :reserved_rooms

  resources :clients do
    resources :reservations
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/base_rate.rb
class BaseRate < ActiveRecord::Base
  attr_accessible :date_begin, :rate
  has_many :rooms
  validates :date_begin, :rate, presence: true
end

app/models/reserved_room.rb
class ReservedRoom < ActiveRecord::Base
  attr_accessible :deleted_at, :priced_at, :reserving, :reservation_id, :room_id
  belongs_to :reservation
  belongs_to :room
  validates :reservation_id, :room_id, presence: true

  scope :not_deleted, -> {
    where(deleted_at: nil)
  }
  scope :deleted, -> {
    where('deleted_at IS NOT NULL')
  }
  scope :overlap, ->(date_in, date_out) {
    joins(:reservation).merge(Reservation.overlap(date_in, date_out))
  }
  scope :unavailable_today, -> {
    where(deleted_at: nil).joins(:reservation).merge(Reservation.today)
  }
  scope :available_today, -> {
    where("reserved_rooms.id NOT IN (?)", unavailable_today)
  }
  def name
    self.room.name
  end
  def rate
    self.room.base_rate.rate
  end
  def view_type
    self.room.view_type
  end
  def room_type
    self.room.room_type
  end
  def clean_up
    self.reservation.date_out == Date.current
  end
end

app/controllers/reserved_rooms_controller.rb
class ReservedRoomsController < ApplicationController
  def index
    if params[:date_in].present? && params[:date_out].present?
      date_in = params[:date_in]
      date_out = params[:date_out]

      @rooms_searched = Room.no_overlap(date_in, date_out)

      if @rooms_searched.empty?
        @rooms_searched = Room.all
      end

      if params[:view_type_id].present?
        @rooms_searched = @rooms_searched.select {|room| (room.view_type_id).to_s == params[:view_type_id]}
      end

      if params[:room_type_id].present?
        @rooms_searched = @rooms_searched.select {|room| (room.room_type_id).to_s == params[:room_type_id]}
      end

      if params[:nb_rooms].present?
        if params[:nb_rooms].to_i > @rooms_searched.length
          @rooms_searched = nil
        end
      end
      @contiguous = []
      if params[:contiguous].present?

        @rooms_searched.each do |room|
          if room.next_door.present?
            @contiguous.append([room, Room.find(room.next_door)])
          end
        end
      end


    else
      @rooms = Room.not_deleted
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @client = Client.find(params[:client_id])

    reservings = @client.reservations.reservings
    reservings.each do |reserving|
      reserving.destroy
    end

    date_in = params[:date_in]
    date_out = params[:date_out]
    @reservation = @client.reservations.new(date_in: date_in, date_out: date_out, reserving: true)
    @reservation.save

    @reserved_rooms = []
    params[:room_ids].each do |room_id|
      reserved_room = ReservedRoom.new
      reserved_room.room_id = room_id
      reserved_room.reservation_id = @reservation.id
      reserved_room.save
      @reserved_rooms.append(reserved_room)
    end
    @rooms = []
    @reserved_rooms.each do |reserved_room|
      @rooms.append(reserved_room.room)
    end
  end

  def create
    @client = Client.find(params[:client_id])

    reservation = @client.reservations.last
    reservation.reserving = false
    reservation.demands = params[:demands]
    reservation.save

    reserved_rooms = reservation.reserved_rooms
    reserved_rooms.each do |reserved_room|
      reserved_room.destroy
    end

    @reserved_rooms = []
    params[:room_ids].each do |room_id|
      reserved_room = ReservedRoom.new
      reserved_room.room_id = room_id
      reserved_room.reservation_id = reservation.id
      reserved_room.save
      @reserved_rooms.append(reserved_room)
    end

    @reserved_rooms.each do |reserved_room|
      reserved_room.priced_at = Billing.calculate_room(reserved_room)
    end

    ClientMailer.billing_reservation(@client).deliver
    redirect_to client_path(@client)
  end

  def destroy
    @reserved_room = ReservedRoom.find(params[:id])
    @reserved_room.update_attribute(:deleted_at, Date.current)
    redirect_to reserved_rooms_path
  end
end

app/helpers/reserved_rooms_helper.rb
module ReservedRoomsHelper
end

app/views/reserved_rooms/_results.html.haml
%div.results

  - if @rooms_searched.present?
    %h2 Rooms available from criteria
    - @rooms = @rooms_searched
  - else
    %h2 Available today

  - if @rooms.present?
    = form_tag new_reserved_room_path, method: :get do
      %table.table.table-hover
        %thead.table-primary
          %tr
            %th Room Name
            %th View Type
            %th Room Type
            %th Price
            %th Selection
        %tbody
          - @rooms.each do |room|
            %tr
              %td= room.name
              %td= room.view_type.name
              %td= room.room_type.name
              %td= number_to_currency(room.rate, unit: "CAD$", format: "%n %u")
              %td= check_box_tag 'room_ids[]', room.id, false, class: "room", onchange: "numberChecked(this)"
      = label_tag "Choose client: "
      = select_tag 'client_id', options_from_collection_for_select(Client.all, "id", :full_name, params[:client_id]), onchange: "reserving(this.value)"
      = link_to "Not in the list?", new_client_path
      = hidden_field_tag "date_in", params[:date_in]
      = hidden_field_tag "date_out", params[:date_out]
      %br/
      = submit_tag "Reserve now", id: "reserve", class: "btn btn-primary disabled", disabled: true
  - else
    %h3 Sorry, no available rooms

app/views/reserved_rooms/_search.html.haml
%h3 Search for available rooms
= form_tag reserved_rooms_path, method: :get, class: "form-group", remote: true do

  = label_tag "Number of rooms"
  = text_field_tag :number_rooms, params[:number_rooms], :onchange => 'checkbox(this)'

  %br/
  = label_tag "Check In: "
  = text_field_tag :date_in, params[:date_in], type: "date", placeholder: "Choose Date"

  %br/
  = label_tag "Check Out: "
  = text_field_tag :date_out, params[:date_out], type: "date", placeholder: "Choose Date"

  %br/
  = label_tag "Type of View: "
  = select_tag :view_type_id, options_from_collection_for_select(ViewType.all, "id", "name", params[:view_type_id]), include_blank: true

  %br/
  = label_tag "Type of Room"
  = select_tag :room_type_id, options_from_collection_for_select(RoomType.all, "id", "name", params[:room_type_id]), include_blank: true
  - if params[:number_rooms].present? and params[:number_rooms] > '1'
    %br/
    = label_tag "Contiguous rooms: "
    = check_box_tag "Contiguous rooms"

  %br/
  = submit_tag "Search"

app/views/reserved_rooms/_search_rooms.html.haml
.needs-validation

  %h3 Search for available rooms
  = form_tag reserved_rooms_path, method: :get, class: "form-group", remote: true do
    %div.form-inline.form-group
      %div.form-inline
        = label_tag "Number of rooms: "
        = text_field_tag :nb_rooms, params[:nb_rooms], id:"nb_rooms", class: "form-control", type: "number", min: "1", onchange: "showContiguous(this.value);", required: true
      %div.form-inline.form-check.d-none
        = label_tag "Contiguous rooms: "
        = check_box_tag :contiguous, params[:contiguous], false, class: "form-check-input", type: "checkbox"
    %div.form-inline.form-group
      %div.form-inline
        = label_tag "Check In: "
        = text_field_tag :date_in, params[:date_in], type: "date", class: "form-control", required: true, id: "date_in", onchange: "beforeToday('#{Date.current}')"
        %div.invalid-feedback
          Check In date can not be before today
      %div.form-inline
        = label_tag "Check Out: "
        = text_field_tag :date_out, params[:date_out], type: "date", class: "form-control", required: true, id: "date_out", onchange: "validateDate(this.value)"
        %div.invalid-feedback
          Check Out date cannot be before Check In date
    %div.form-inline.form-group
      %div.form-inline
        = label_tag "Type of View: "
        = select_tag :view_type_id, options_from_collection_for_select(ViewType.all, "id", "name", params[:view_type_id]), include_blank: true, class: "form-control"
      %div.form-inline
        = label_tag "Type of Room"
        = select_tag :room_type_id, options_from_collection_for_select(RoomType.all, "id", "name", params[:room_type_id]), include_blank: true, class: "form-control"
      
    = submit_tag "Search", class: "btn btn-primary", id: "search"

app/views/reserved_rooms/index.html.haml
.container-fluid
  = render 'search_rooms'
  %br/
  = render 'results', rooms: @rooms

app/views/reserved_rooms/index.js.erb
$('.search').html("<%= j (render 'search') %>");

$('.results').html("<%= j (render 'results', rooms: @rooms) %>");

app/views/reserved_rooms/new.html.haml
.container
  %h1 Reserving rooms

  = form_tag action: :create , class: "form-group" do
    = label_tag "Client: "
    = @client.full_name
    = hidden_field_tag :client_id, @client.id

    %br/
    = label_tag "Reservation from"
    = @reservation.date_in
    = hidden_field_tag :date_in, params[:date_in]
    = label_tag "to"
    = @reservation.date_out
    = hidden_field_tag :date_out, params[:date_out]
    %br/
    %table.table.table-hover
      %thead.table-primary
        %tr
          %th Room Name
          %th View Type
          %th Room Type
          %th Price
      %tbody
        - @rooms.each do |room|
          %tr
            %td= room.name
            %td= room.view_type.name
            %td= room.room_type.name
            %td= number_to_currency(room.rate, unit: "CAD$", format: "%n %u")
            %td.d-none= check_box_tag 'room_ids[]', room.id, value: true
    .form-group
      = label_tag "Demands: "
      = text_area_tag :demands, params[:demands], cols: 30, row: 5, class: "form-control"

    = submit_tag "Confirm", class: "btn btn-primary"