config/routes.rb
HotelNagano::Application.routes.draw do

  resources :billing

  namespace :admin do
    resources :clients
    resources :reservations
    resources :rooms
    resources :statistics
  end

  resources :reserved_rooms

  resources :clients do
    resources :reservations
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :deleted_at, :email, :first_name, :last_name
  has_many :reservations, :dependent => :destroy
  has_many :reserved_rooms, :through => :reservations
  validates :email, :first_name, :last_name, presence: true
  validates :email, uniqueness: true
  scope :not_deleted, -> {
    where(deleted_at: nil)
  }
  scope :with_reservations, -> { joins(:reservations)}
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < ApplicationController
  def index
    @clients = Client.not_deleted
  end

  def edit
    @client = Client.find(params[:id])
  end

  def show
    @client = Client.find(params[:id])
    @reservations = @client.reservations
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        ClientMailer.welcome_email(@client).deliver

        format.html  { redirect_to([:admin, @client],
                                   :notice => 'Client was successfully created.') }
        format.json  { render :json => @client,
                              :status => :created, :location => @client }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @client.errors,
                              :status => :unprocessable_entity }
      end
    end
  end

  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html  { redirect_to([:admin, @client],
                                   :notice => 'Client was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @client.errors,
                              :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.update_attribute(:deleted_at, Date.current)
    @client.reservations.update_all(deleted_at: Date.current)
    @client.reserved_rooms.update_all(deleted_at: Date.current)

    respond_to do |format|
      format.html { redirect_to admin_clients_url }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.not_deleted
  end

  def edit
    @client = Client.find(params[:id])
  end

  def show
    @client = Client.find(params[:id])
    @reservations = @client.reservations
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        ClientMailer.welcome_email(@client).deliver

        format.html  { redirect_to(@client,
                                   :notice => 'Client was successfully created.') }
        format.json  { render :json => @client,
                              :status => :created, :location => @client }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @client.errors,
                              :status => :unprocessable_entity }
      end
    end
  end

  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html  { redirect_to(@client,
                                   :notice => 'Client was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @client.errors,
                              :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.haml
.needs-validation
  = form_for(@client, :html => {:class => "form-group"}) do |f|
    - if @client.errors.any?
      #errorExplanation
        %h2
          = pluralize(@client.errors.count, "error")
          prohibited
          this client from being saved:
        %ul
          - @client.errors.full_messages.each do |msg|
            %li= msg
    .field
      = f.label :first_name
      %br/
      = f.text_field :first_name, class: "form-control", placeholder: "François", autocomplete: "off", required: true
    .field
      = f.label :last_name
      %br/
      = f.text_field :last_name, class: "form-control", placeholder: "Lecave", autocomplete: "off", required: true
    .field
      = f.label :email
      %br/
      = f.email_field :email, class: "form-control", placeholder: "François.Lecave@gros.gouv.suce.culsec.ca", autocomplete: "off", required: true
    %br/
    .actions
      = f.submit(class: "btn btn-primary")

app/views/clients/edit.html.haml
.container-fluid
  %h1 Editing client
  = render 'form'
  = link_to 'Show', @client
  |
  = link_to 'Back', clients_path

app/views/clients/index.html.haml
.container-fluid
  %h2 Listing clients
  %table.table.table-hover
    %thead.table-primary
      %tr
        %th First Name
        %th Last Name
        %th Email
        %th
    %tbody
      - @clients.each do |client|
        %tr
          %td= client.first_name
          %td= client.last_name
          %td= client.email
          %td= link_to 'Show', client

  = link_to 'New Client', new_client_path

app/views/clients/new.html.haml
.container-fluid
  %h1 New client
  = render 'form'
  = link_to 'Back', clients_path

app/views/clients/show.html.haml
.container-fluid
  %p#notice= notice
  %p
    %b First Name:
    = @client.first_name
  %p
    %b Last Name:
    = @client.last_name
  %p
    %b Email:
    = @client.email

  - if @reservations.any?
    %h2 Reservations
    %table.table.table-hover
      %thead.table-primary
        %tr
          %th Check In
          %th Check Out
          %th Demands
          %th Reserved rooms
          %th
          %th
      %tbody
        - @reservations.each do |reservation|
          %tr
            %td= reservation.date_in
            %td= reservation.date_out
            %td= reservation.demands
            %td= (reservation.rooms.map{|room| room.name}).join(', ')
            %td= link_to "Show", client_reservation_path(reservation)
            %td= link_to "Billing", billing_path(reservation)

  = link_to 'Edit', edit_client_path(@client)
  |
  = link_to 'Back', clients_path