config/routes.rb
HotelNagano::Application.routes.draw do

  resources :billing

  namespace :admin do
    resources :clients
    resources :reservations
    resources :rooms
    resources :statistics
  end

  resources :reserved_rooms

  resources :clients do
    resources :reservations
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :deleted_at, :email, :first_name, :last_name
  has_many :reservations, :dependent => :destroy
  has_many :reserved_rooms, :through => :reservations
  validates :email, :first_name, :last_name, presence: true
  validates :email, uniqueness: true
  scope :not_deleted, -> {
    where(deleted_at: nil)
  }
  scope :with_reservations, -> { joins(:reservations)}
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :client_id, :date_in, :date_out, :deleted_at, :demands, :billing_id, :reserving
  belongs_to :client
  belongs_to :billing
  has_many :reserved_rooms, dependent: :destroy
  has_many :rooms, :through => :reserved_rooms
  validates :client_id, :date_in, :date_out, presence: true
  validate :dates

  scope :reservings, -> {
    where(reserving: true)
  }
  scope :not_deleted, -> {
    where(deleted_at: nil)
  }
  scope :overlap, ->(date_in, date_out){
    where("? BETWEEN date_in AND date_out OR ? BETWEEN date_in AND date_out ", date_in, date_out)
  }
  scope :today, -> {
    where("? BETWEEN date_in AND date_out", Date.current)
  }
  def duration
    (date_out - date_in).to_i + 1
  end

  private

  def dates
    return if date_in.blank? || date_out.blank?
    if date_in < Date.current
      errors.add(:date_in, "cannot be before today")
    end
    if date_out < date_in
      errors.add(:date_out, "cannot be before date_in")
    end
  end
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < ApplicationController
  def index
    @clients = Client.not_deleted
  end

  def edit
    @client = Client.find(params[:id])
  end

  def show
    @client = Client.find(params[:id])
    @reservations = @client.reservations
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        ClientMailer.welcome_email(@client).deliver

        format.html  { redirect_to([:admin, @client],
                                   :notice => 'Client was successfully created.') }
        format.json  { render :json => @client,
                              :status => :created, :location => @client }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @client.errors,
                              :status => :unprocessable_entity }
      end
    end
  end

  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html  { redirect_to([:admin, @client],
                                   :notice => 'Client was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @client.errors,
                              :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.update_attribute(:deleted_at, Date.current)
    @client.reservations.update_all(deleted_at: Date.current)
    @client.reserved_rooms.update_all(deleted_at: Date.current)

    respond_to do |format|
      format.html { redirect_to admin_clients_url }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < ApplicationController
  def index
    @reservations = Reservation.order(:date_in).not_deleted
  end

  def show
    @reservation = Reservation.find(params[:id])
    @client = @reservation.client
    @billing = @reservation.billing
    @room_names = []
    @reservation.reserved_rooms.each do |reserved_room|
      @room_names.append(reserved_room.name)
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
    @client = @reservation.client
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @client = Client.find(params[:client_id])
    @reservation = @client.reservations.create(params[:reservation])
    @reserved_rooms.each do |reserved_room|
      reserved_room.reservation_id = @reservation.id
      reserved_room.save
    end
    redirect_to client_path(@client)
  end

  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html  { redirect_to(@reservation,
                                   :notice => 'Reservation was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @reservation.errors,
                              :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.update_attribute(:deleted_at, Date.current)
    @reservation.reserved_rooms.update_all(deleted_at: Date.current)

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.not_deleted
  end

  def edit
    @client = Client.find(params[:id])
  end

  def show
    @client = Client.find(params[:id])
    @reservations = @client.reservations
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        ClientMailer.welcome_email(@client).deliver

        format.html  { redirect_to(@client,
                                   :notice => 'Client was successfully created.') }
        format.json  { render :json => @client,
                              :status => :created, :location => @client }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @client.errors,
                              :status => :unprocessable_entity }
      end
    end
  end

  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html  { redirect_to(@client,
                                   :notice => 'Client was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @client.errors,
                              :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.order(:date_in).not_deleted
  end

  def show
    @reservation = Reservation.find(params[:id])
    @client = @reservation.client
    @billing = @reservation.billing
    @room_names = []
    @reservation.reserved_rooms.each do |reserved_room|
      @room_names.append(reserved_room.name)
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
    @client = @reservation.client
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @client = Client.find(params[:client_id])
    @reservation = @client.reservations.create(params[:reservation])
    @reserved_rooms.each do |reserved_room|
      reserved_room.reservation_id = @reservation.id
      reserved_room.save
    end
    redirect_to client_path(@client)
  end

  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html  { redirect_to(@reservation,
                                   :notice => 'Reservation was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @reservation.errors,
                              :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.reserved_rooms.update_all(deleted_at: Date.current)
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/clients/reservations/_form.html.haml
= form_for(@reservation, html: {:class => "form-group"}) do |f|
  - if @reservation.errors.any?
    #errorExplanation
      %h2
        = pluralize(@reservation.errors.count, "error")
        prohibited
        this reservation from being saved:
      %ul
        - @reservation.errors.full_messages.each do |msg|
          %li= msg
  .field
    = label_tag "Client: "
    = @client.full_name
  .field
    = f.label "Check In"
    %br/
    = f.text_field :date_in, type: "date", class: "form-control", autocomplete: "off", required: true
  .field
    = f.label "Check Out"
    %br/
    = f.text_field :date_out, type: "date", class: "form-control", autocomplete: "off", required: true
  .field
    = f.label "Demands"
    %br/
    = f.text_area :demands, type: "text-area", class: "form-control", rows: "2"
    %br/
  .actions
    = f.submit(class: "btn btn-primary")

app/views/clients/reservations/_form_client.html.haml
= form_for([@client, @client.reservations.build]) do |f|
  .field
    = f.label "Date Check In"
    %br/
    = f.text_field :date_in, 'data-behaviour' => 'datepicker'
  .field
    = f.label "Date Check Out"
    %br/
    = f.text_field :date_out, 'data-behaviour' => 'datepicker'
  .field
    = f.label :demands
    %br/
    = f.text_area :demands, cols: 30, rows: 5

  .actions
    = f.submit

app/views/clients/reservations/_reservation.html.haml
%p
  %b Date in:
  = reservation.date_in

%p
  %b Date out:
  = reservation.date_out

%p
  %b Demands:
  = reservation.demands

%p
  %b Date created:
  =(reservation.created_at).to_date
%br/

app/views/clients/reservations/destroy.js.erb
$('.delete_reservation').bind('ajax:success', function() {
    $(this).closest('tr').fadeOut();
});

app/views/clients/reservations/edit.html.haml
.container
  %h1 Editing reservation
  = render 'form'
  = link_to 'Show', admin_reservation_path(@reservation)
  |
  = link_to 'Back', admin_reservations_path

app/views/clients/reservations/index.html.haml
.container-fluid
  %h1 Reservations
  %table.table.table-hover
    %thead.table-primary
      %tr
        %th Check In
        %th Check Out
        %th Client
        %th
        %th
        %th
    - @reservations.each do |reservation|
      %tr
        %td= reservation.date_in
        %td= reservation.date_out
        %td= link_to reservation.client.full_name, admin_client_path(reservation.client)
        %td= link_to 'Show', admin_reservation_path(reservation)
        %td= link_to 'Edit', edit_admin_reservation_path(reservation)
        %td= link_to 'Delete', admin_reservation_path(reservation), method: :delete, data: { confirm: 'Are you sure?' },
        remote: true, class: 'delete_reservation'
  %br/
  = link_to 'New Reservation', reserved_rooms_path

app/views/clients/reservations/new.html.haml
%h1 New reservation

= form_tag new_reservation_path, method: :get do
  = label_tag "Choose client: "
  = select_tag :client_id, options_from_collection_for_select(Client.all, "id", :full_name, params[:client_id]), include_blank: true, :onchange => 'this.form.submit();'
  = link_to "Not in the list?", new_client_path
  %br/

- if params[:client_id].present?
  - @client = Client.find(params[:client_id])
  = render 'form_client'

= link_to 'Back', reservations_path